# Generated by Django 5.2.3 on 2025-06-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=10)),
                ('slug_content', models.TextField()),
                ('time_limit', models.TimeField()),
            ],
        ),
    ]
