# Generated by Django 5.2.3 on 2025-06-12 16:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SlugCpPaster', '0003_alter_slug_created_time_alter_slug_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slug',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
